### PR TITLE
Add configuration panel on demo page

### PR DESCRIPTION
**Pull request by smknstd**
inspired by https://unsplash.github.io/react-trend/

I think I fixed rounding and label size in the process. 

Still found problems with
- padding (seems broken)
- gradient (some colors combinations have strange behaviour)
- labels (when labelRotate=90, it seems not well aligned)

Screenshot from 2020-05-30 20-40-48

Screenshot from 2020-05-30 20-40-25

### CODE REVIEW

**Review by DeviaVir — APPROVED** [review]
:+1: this is a great addition, I'll merge it in to see how it looks

**Comment by smknstd** [comment]
hi @DeviaVir, did you plan to update the gh-pages branch as well ?

**Comment by DeviaVir** [comment]
Hi @smknstd, plan on, yes.   Trying to remember how I set this up, last touched it 3 years ago :)

**Comment by smknstd** [comment]
Would you accept some help with the project, I'd like to help

**Comment by DeviaVir** [comment]
Certainly, I have moved on to different areas since.

**Pull request merged**
