### PR TITLE
issue/7 Negative Bars

### PR DESCRIPTION
**Pull request by zombiesplat**
Adding ability for negative numbers
Adding a minimum bar height to avoid ugly math when
the value is zero

### CODE REVIEW

**Comment by zombiesplat** [comment]
So I just realized that the additional work I did last night for some other stuff is showing in this PR. If you get around to looking at this, and you like the changes, let me know and I'll fix my PR against the first commit.

**Comment by zombiesplat** [comment]
Which btw, the more recent commit deals with the issue about labels.

**Comment by DeviaVir** [comment]
https://jsfiddle.net/d3Lbnagc/
https://jsfiddle.net/d3Lbnagc/1/

Seems to work fine.

Thank you for contributing!

**Comment by DeviaVir** [comment]
included in 0.1.5 release https://www.npmjs.com/package/vuebars

**Pull request merged**
