### PR TITLE
Segregate Labels

### PR DESCRIPTION
**Pull request by zombiesplat**
This fixes the problem where labels are automatically used. 

in order to use labels, you must pass in an Array[] of strings that correlate to the bars data

the prop is `label-data`
```
          <bars
            v-if="data"
            class="minimal-bars"
            :data="data"
            :label-data="labels"
            :barWidth="10"
            auto-draw
            smooth
            :gradient="gradient"
            :width="120"
            :height="56"
            :padding="1"
            :min-bar-height="minBarHeight"
            :label-rotate="labelRotate"
            :label-color="labelColor"
          ></bars>

    props: {
      dark: Boolean,
      reverse: Boolean,
      data: Array,
      icon: String,
      title: String,
      subTitle: String,
      color: String,
      applyTitleColor: Boolean,
      gradient: Array,
      minBarHeight: Number,
      labelRotate: Number,
      labelColor: String,
      labels: Array,
    },
```

### CODE REVIEW

**Comment by zombiesplat** [comment]
so it looks like I have some merge conflicts because I didn't start with the latest branch. I'm trying to figure out how to get my fork updated, but patching doesn't seem to help. I'll look at this soon as I can, but if you can suss out the problem without me, let me know.

**Comment by zombiesplat** [comment]
I figured it out. set upstream and then merge locally. so I did that and made sure the labelSize changes got ported to my changes as well.

hopefully this is all good. sorry it took a while to get to it.

**Review by DeviaVir — APPROVED** [review]
:+1: looks good, sorry for the delay on getting this in

**Comment by smknstd** [comment]
@DeviaVir As said by @zombiesplat [here](https://github.com/DeviaVir/vue-bar/issues/20), this PR introduced breaking changes. Did you plan to create a new major version number ?

**Pull request merged**
